# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: antananarywaishorselikingcanal
      POSTGRES_USER: wildhorses
      POSTGRES_DB: db_name
